#!/bin/bash

pacman -Qdtq
if [ $? -ne 0 ]; then
    echo "==> no orphans found"
fi

# printf "do you want to remove orphans? [y/n] "
# read answer
#
# if [[ "$answer" == "Y" || "$answer" == "y" ]]; then
# 	sudo pacman -Rns $(pacman -Qtdq);
# fi
